name: uploader

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install python requirements
      run: pip install requests m3u8
    - name: checkout repo content
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.REPO }}
        token: ${{ secrets.PAT }}
    - name: start script
      env:
        PAT: ${{ secrets.PAT }}
        REPO: ${{ secrets.REPO }}
      run: |
        sudo apt update
        sudo apt install ffmpeg
        python main.py > log
